export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

export const GET_TOPRATED_MOVIES_REQUEST = 'GET_TOPRATED_MOVIES_REQUEST';
export const GET_TOPRATED_MOVIES_SUCCESS = 'GET_TOPRATED_MOVIES_SUCCESS';
export const GET_TOPRATED_MOVIES_FAIL = 'GET_TOPRATED_MOVIES_FAIL';

export const GET_POPULAR_MOVIES_REQUEST = 'GET_POPULAR_MOVIES_REQUEST';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAIL = 'GET_POPULAR_MOVIES_FAIL';

export const GET_ALLTIME_BEST_MOVIE_REQUEST = 'GET_ALLTIME_BEST_MOVIE_REQUEST';
export const GET_ALLTIME_BEST_MOVIE_SUCCESS = 'GET_ALLTIME_BEST_MOVIE_SUCCESS';
export const GET_ALLTIME_BEST_MOVIE_FAIL = 'GET_ALLTIME_BEST_MOVIE_FAIL';

export const GET_UPCOMING_MOVIES_REQUEST = 'GET_UPCOMING_MOVIES_REQUEST';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_FAIL = 'GET_UPCOMING_MOVIES_FAIL';

export const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAIL = 'GET_MOVIE_DETAILS_FAIL';

export const GET_CREDITS_REQUEST = 'GET_CREDITS_REQUEST';
export const GET_CREDITS_SUCCESS = 'GET_CREDITS_SUCCESS';
export const GET_CREDITS_FAIL = 'GET_CREDITS_FAIL';

export const GET_RECOMMENDATIONS_REQUEST = 'GET_RECOMMENDATIONS_REQUEST';
export const GET_RECOMMENDATIONS_SUCCESS = 'GET_RECOMMENDATIONS_SUCCESS';
export const GET_RECOMMENDATIONS_FAIL = 'GET_RECOMMENDATIONS_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
